name: easy_meal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  intl: ^0.20.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  flutter_launcher_icons: ^0.14.4
  expandable_text: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
